name: RPL
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9       # specify major+minor only to allow any 3.9.x
  - pip              # latest pip
  - bzip2            # allow latest compatible bzip2
  - zlib             # core compression library
  - xz               # provides liblzma
  - sqlite           # core database library
  - libffi           # foreign-function interface
  - openssl          # TLS/SSL support
  - pyyaml           # YAML parsing
  - readline         # interactive input
  - setuptools       # packaging support
  - tk               # GUI toolkit for tkinter
  - tzdata           # timezone data
  - wheel            # binary package format
  - pip:
      - blinker==1.9.0
      - click==8.1.8
      - flask==2.3.3
      - importlib-metadata==8.6.1
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - numpy==1.21.2
      - plotly==5.3.1
      - pyserial==3.5
      - six==1.17.0
      - tenacity==9.0.0
      - werkzeug==2.3.7
      - zipp==3.21.0