# BLAST Web and Data Configuration

# Data Source
data_source: "simulator"  # or "serial"

# Serial Configuration
serial_port: "/dev/cu.usbmodem1201"
serial_baudrate: 9600

# subpage 1
subpage1:
  title: "Pressure Transducers"
  description: "Pressure measurements from pressure transducers"
  pressure_transducers:
    - name: "GN2"
      id: "pt1"
      min_value: -50
      max_value: 500
      warning_value: 250
      danger_value: 400
    - name: "LOX"
      id: "pt2"
      min_value: -50
      max_value: 500
      warning_value: 250
      danger_value: 400
    - name: "LNG"
      id: "pt3"
      min_value: -50
      max_value: 500
      warning_value: 250
      danger_value: 400
    - name: "Pressure Transducer 4"
      id: "pt4"
      min_value: -50
      max_value: 500
      warning_value: 250
      danger_value: 400
    - name: "Pressure Transducer 5"
      id: "pt5"
      min_value: -50
      max_value: 500
      warning_value: 250
      danger_value: 400

# subpage 2
subpage2:
  title: "Thermocouples & Load Cells"
  description: "Temperature measurements from thermocouples and load cells"
  thermocouples:
    - name: "Thermocouple 1"
      id: "tc1"
      min_value: 0
      max_value: 1000
      warning_value: 500
      danger_value: 800
    - name: "Thermocouple 2"
      id: "tc2"
      min_value: 0
      max_value: 1000
      warning_value: 500
      danger_value: 800
    - name: "Thermocouple 3"
      id: "tc3"
      min_value: 0
      max_value: 1000
      warning_value: 500
      danger_value: 800
  load_cells:
    - name: "Load Cell 1"
      id: "lc1"
      min_value: 0
      max_value: 500
      warning_value: 250
      danger_value: 400
    - name: "Load Cell 2"
      id: "lc2"
      min_value: 0
      max_value: 500
      warning_value: 250
      danger_value: 400
    - name: "Load Cell 3"
      id: "lc3"
      min_value: 0
      max_value: 500
      warning_value: 250
      danger_value: 400

# subpage 3
subpage3:
  title: "Flow Control Valves"
  description: "Flow control measurements from flow control valves"
  flow_control_valves:
    - name: "Flow Control Valve 1"
      id: "fv1"
    - name: "Flow Control Valve 2"
      id: "fv2"
    - name: "Flow Control Valve 3"
      id: "fv3"
    - name: "Flow Control Valve 4"
      id: "fv4"
    - name: "Flow Control Valve 5"
      id: "fv5"
    - name: "Flow Control Valve 6"
      id: "fv6"
  flow_control_valve_groups:
    - name: "Left Triple"
      id: "left_triple"
      valves: ["fv1", "fv2", "fv3"]
    - name: "Right Triple"
      id: "right_triple"
      valves: ["fv4", "fv5", "fv6"]
    - name: "All Valves"
      id: "all_valves"
      valves: ["fv1", "fv2", "fv3", "fv4", "fv5", "fv6"]