# BLAST Web and Data Configuration

# Data Source
data_source: "simulator"  # or "serial"

# Serial Configuration
serial_port: "/dev/cu.usbmodem1201"
serial_baudrate: 9600

# subpage 1
subpage1:
  title: "Pressure Transducers"
  description: "Pressure measurements from pressure transducers"
  pressure_transducers:
    - name: "GN2"
      id: "pt1"
      color: "#0072B2"  # Blue
      min_value: -50
      max_value: 500
      warning_value: 250
      danger_value: 400
    - name: "LOX"
      id: "pt2"
      color: "#E69F00"  # Orange
      min_value: -50
      max_value: 500
      warning_value: 250
      danger_value: 400
    - name: "LNG"
      id: "pt3"
      color: "#56B4E9"  # Light Blue
      min_value: -50
      max_value: 500
      warning_value: 250
      danger_value: 400
    - name: "Pressure Transducer 4"
      id: "pt4"
      color: "#009E73"  # Teal
      min_value: -50
      max_value: 500
      warning_value: 250
      danger_value: 400
    - name: "Pressure Transducer 5"
      id: "pt5"
      color: "#CC79A7"  # Pink
      min_value: -50
      max_value: 500
      warning_value: 250
      danger_value: 400

# subpage 2
subpage2:
  title: "Thermocouples & Load Cells"
  description: "Temperature measurements from thermocouples and load cells"
  thermocouples:
    - name: "Thermocouple 1"
      id: "tc1"
      color: "#CC79A7"  # Pink
      min_value: 0
      max_value: 1000
      warning_value: 500
      danger_value: 800
    - name: "Thermocouple 2"
      id: "tc2"
      color: "#009E73"  # Teal
      min_value: 0
      max_value: 1000
      warning_value: 500
      danger_value: 800
    - name: "Thermocouple 3"
      id: "tc3"
      color: "#D55E00"  # Dark Orange
      min_value: 0
      max_value: 1000
      warning_value: 500
      danger_value: 800
  load_cells:
    - name: "Load Cell 1"
      id: "lc1"
      color: "#F0E442"  # Yellow
      min_value: 0
      max_value: 1000
      warning_value: 250
      danger_value: 400
    - name: "Load Cell 2"
      id: "lc2"
      color: "#000000"  # Black
      min_value: 0
      max_value: 1000
      warning_value: 250
      danger_value: 400
    - name: "Load Cell 3"
      id: "lc3"
      color: "#999999"  # Gray
      min_value: 0
      max_value: 1000
      warning_value: 250
      danger_value: 400

# subpage 3
subpage3:
  title: "Flow Control Valves"
  description: "Flow control measurements from flow control valves"
  flow_control_valves:
    - name: "Flow Control Valve 1"
      id: "fv1"
    - name: "Flow Control Valve 2"
      id: "fv2"
    - name: "Flow Control Valve 3"
      id: "fv3"
    - name: "Flow Control Valve 4"
      id: "fv4"
    - name: "Flow Control Valve 5"
      id: "fv5"
    - name: "Flow Control Valve 6"
      id: "fv6"
    - name: "Flow Control Valve 7"
      id: "fv7"
