# BLAST Logging Configuration

logging:
  # Global logging level
  level: DEBUG
  
  # Async queue configuration
  async:
    enabled: true
    queue_size: 10000
    batch_size: 50
    batch_timeout_ms: 100
  
  # Log handlers configuration
  handlers:
    events:
      type: rotating_file
      path: logs/events/
      filename: events.log
      max_bytes: 104857600  # 100MB
      backup_count: 7
      level: INFO
      format: json
    
    errors:
      type: rotating_file
      path: logs/errors/
      filename: errors.log
      max_bytes: 52428800   # 50MB
      backup_count: 14
      level: ERROR
      format: detailed
    
    performance:
      type: rotating_file
      path: logs/performance/
      filename: perf.log
      max_bytes: 104857600  # 100MB
      backup_count: 7
      level: DEBUG
      format: json
    
    serial:
      type: rotating_file
      path: logs/serial/
      filename: serial.log
      max_bytes: 52428800   # 50MB
      backup_count: 7
      level: DEBUG
      format: standard
    
    console:
      type: stream
      level: INFO
      format: standard
  
  # Monitoring configuration
  monitors:
    freeze_detection:
      enabled: true
      timeout_seconds: 5.0
      heartbeat_interval: 1.0
      dump_on_freeze: true
    
    memory:
      enabled: true
      check_interval: 60.0
      threshold_mb: 500
      log_on_threshold: true
    
    performance:
      enabled: true
      sample_interval: 1.0
      log_interval: 60.0
      
    client_monitoring:
      enabled: true
      throttle_threshold_ms: 2000
      inactive_threshold_ms: 10000
      max_clients_tracked: 100
  
  # Sensor threshold monitoring
  thresholds:
    log_warnings: true
    log_dangers: true
    
  # Debug options
  debug:
    log_serial_hex: false
    log_all_requests: false
    verbose_errors: true