"""
BLAST Serial Monitor Buffer - In-memory ring buffer for serial monitor display.
Captures every raw data packet from both serial and simulator sources.
"""

import time
import threading
from collections import deque
from datetime import datetime
from typing import Dict, List, Any


class SerialMonitorBuffer:
    """Thread-safe ring buffer that stores raw serial lines for the Serial Monitor UI."""

    def __init__(self, maxlen: int = 1000):
        self._lines: deque = deque(maxlen=maxlen)
        self._index: int = 0  # Global monotonic index
        self._lock = threading.Lock()

    def add_line(self, raw_data: str, source: str = "serial") -> None:
        """Add a raw data line to the buffer.

        Args:
            raw_data: The raw string as received from serial / generated by simulator.
            source: 'serial' or 'simulator' to indicate origin.
        """
        now = time.time()
        dt = datetime.fromtimestamp(now)
        timestamp_str = dt.strftime("%H:%M:%S.") + f"{dt.microsecond // 1000:03d}"

        with self._lock:
            self._lines.append({
                "index": self._index,
                "timestamp": timestamp_str,
                "raw": raw_data,
                "source": source,
            })
            self._index += 1

    def get_lines(self, after_index: int = -1) -> Dict[str, Any]:
        """Return all lines with index > after_index (for incremental polling).

        Args:
            after_index: Return only lines newer than this index.
                         Pass -1 to get all buffered lines.

        Returns:
            {"lines": [...], "next_index": int}
        """
        with self._lock:
            if after_index < 0:
                result = list(self._lines)
            else:
                result = [entry for entry in self._lines if entry["index"] > after_index]
            next_idx = self._index
        return {"lines": result, "next_index": next_idx}
